[profile.default]
src = 'sol/contracts'
test = 'sol/tests'
script = 'sol/scripts'
out = 'build/foundry-artifacts'
cache_path = 'build/foundry-cache'
libs = ['lib']

remappings = [
]

fs_permissions = [{ access = "write", path = "./exports" }]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
sepolia = "${RPC_SEPOLIA}"
optimism = "${RPC_OPTIMISM}"
optimismGoerli = "${RPC_OPTIMISM_GOERLI}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
polygonMumbai = "${RPC_POLYGON_MUMBAI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrumGoerli = "${RPC_ARBITRUM_GOERLI}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"

[etherscan]
mainnet = { key="${ETHERSCAN_API_KEY_MAINNET}", chainId=1 }
optimism = { key="${ETHERSCAN_API_KEY_OPTIMISM}", chainId=10 }
avalanche = { key="${ETHERSCAN_API_KEY_AVALANCHE}", chainId=43114 }
polygon = { key="${ETHERSCAN_API_KEY_POLYGON}", chainId=137 }
arbitrum = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chainId=42161 }
fantom = { key="${ETHERSCAN_API_KEY_FANTOM}", chainId=250 }
metis = { key="any", chainId=1088, url='https://andromeda-explorer.metis.io/' }

# See more config options https://github.com/gakonst/foundry/tree/master/config
