[profile.default]
src = 'sol/contracts'
test = 'sol/tests'
script = 'sol/scripts'
out = 'build/foundry-artifacts'
cache_path = 'build/foundry-cache'
libs = ['lib']

remappings = [
]

fs_permissions = [{ access = "write", path = "./exports" }]

[rpc_endpoints]
arbitrum = "${RPC_ARBITRUM}"
arbitrumGoerli = "${RPC_ARBITRUM_GOERLI}"
arbitrumNova = "${RPC_ARBITRUM_NOVA}"
mainnet = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
sepolia = "${RPC_SEPOLIA}"
optimism = "${RPC_OPTIMISM}"
optimismGoerli = "${RPC_OPTIMISM_GOERLI}"
bsc = "${RPC_BSC}"
polygon = "${RPC_POLYGON}"
polygonMumbai = "${RPC_POLYGON_MUMBAI}"
polygonZkEvm = "${RPC_POLYGON_ZKEVM}"
polygonZkEvmTestnet = "${RPC_POLYGON_ZKEVM_TESTNET}"
moonbeam = "${RPC_MOONBEAM}"
moonriver = "${RPC_MOONRIVER}"
gnosis = "${RPC_GNOSIS}"
avax = "${RPC_AVAX}"
fantom = "${RPC_FANTOM}"
celo = "${RPC_CELO}"
harmony = "${RPC_HARMONY}"
metis = "${RPC_METIS}"
aurora = "${RPC_AURORA}"
zkSync = "${RPC_ZKSYNC}"
zkSyncTestnet = "${RPC_ZKSYNC_TESTNET}"

[etherscan]
arbitrum = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chain=42161, url="https://api.arbiscan.io/api" }
arbitrumNova = { key="${ETHERSCAN_API_KEY_ARBITRUM_NOVA}", chain=42170, url="https://api-nova.arbiscan.io/api" }
arbitrumGoerli = { key="${ETHERSCAN_API_KEY_ARBITRUM}", chain=421613, url="https://api-goerli.arbiscan.io/api" }
mainnet = { key="${ETHERSCAN_API_KEY_MAINNET}" }
goerli = { key="${ETHERSCAN_API_KEY_GOERLI}", url="https://api-goerli.etherscan.io/api" }
sepolia = { key="${ETHERSCAN_API_KEY_SEPOLIA}", chain=11155111, url="https://api-sepolia.etherscan.io/api" }
optimism = { key="${ETHERSCAN_API_KEY_OPTIMISM}", chain=10, url="https://api-optimistic.etherscan.io/api" }
optimismGoerli = { key="${ETHERSCAN_API_KEY_OPTIMISM_GOERLI}", chain=420, url="http://api-goerli-optimism.etherscan.io/api" }
polygon = { key="${ETHERSCAN_API_KEY_POLYGON}", chain=137, url="https://api.polygonscan.com/api" }
polygonMumbai = { key="${ETHERSCAN_API_KEY_POLYGON_MUMBAI}", chain=80001, url="https://api-testnet.polygonscan.com/api" }
polygonZkEvm = { key="${ETHERSCAN_API_KEY_POLYGON_ZKEVM}", chain=1101, url="https://api-zkevm.polygonscan.com/api" }
polygonZkEvmTestnet = { key="${ETHERSCAN_API_KEY_POLYGON_ZKEVM_TESTNET}", chain=1442 , url="https://api-testnet-zkevm.polygonscan.com/api" }
bsc = { key="${ETHERSCAN_API_KEY_BSC}", chain=56, url="https://api.bscscan.com/api" }
moonbeam = { key="${ETHERSCAN_API_KEY_MOONBEAM}", chain=1284, url="https://api-moonbeam.moonscan.io/api" }
moonriver = { key="${ETHERSCAN_API_KEY_MOONRIVER}", chain=1285, url="https://api-moonriver.moonscan.io/api" }
gnosis = { key="${ETHERSCAN_API_KEY_GNOSIS}", chain=100, url="https://api.gnosisscan.io/api" }
avax = { key="${ETHERSCAN_API_KEY_AVAX}", chain=43114, url="https://api.snowtrace.io/api" }
fantom = { key="${ETHERSCAN_API_KEY_FANTOM}", chain=250, url="https://api.ftmscan.com/api" }
celo = { key="${ETHERSCAN_API_KEY_CELO}", chain=42220, url="https://api.celoscan.io/api" }
metis = { key="any", chain=1088,  url="https://andromeda-explorer.metis.io/api" }
aurora = { key="any", chain=421613, url="https://explorer.mainnet.aurora.dev/api" }
zkSync = { key="any", chain=324, url="https://zksync2-mainnet-explorer.zksync.io/contract_verification" }
zkSyncTestnet = { key="any", chain=280, url="https://zksync2-testnet-explorer.zksync.dev/contract_verification" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
