name: main
on: [push, workflow_dispatch]
jobs:
  foundry:
    name: foundry tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy env
        run: cp .env.example .env

      - uses: actions/setup-node@v3
        with:
          node-version: "19.0"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge test
  hardhat:
    if: github.event_name == 'workflow_dispatch'
    name: hardhat tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy env
        run: cp .env.example .env

      - uses: actions/setup-node@v3
        with:
          node-version: "19.0"

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm i --ignore-scripts

      - run: pnpm hh:test
